default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.76.0
    hooks:
      - id: oxlint
        name: lint JS/TS and Vue files
        types_or: [javascript, jsx, ts, tsx, vue]
        args: ["--disable-nested-config"]

  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.61.0
    hooks:
      - id: oxfmt
        name: check formatting

  - repo: https://github.com/Weburz/crisp
    rev: v1.0.0
    hooks:
      - id: crisp
        stages: [commit-msg]
        name: lint git-commit messages
