default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.15.1
    hooks:
      - id: hadolint
        name: lint Dockerfiles

  - repo: local
    hooks:
      - id: eslint
        name: lint JS/TS and Vue files
        entry: pnpm exec eslint
        language: system
        types_or: [vue, javascript, ts]
        pass_filenames: true
      - id: prettier
        name: check formatting
        entry: pnpm exec prettier --check
        language: system
        types_or: [vue, javascript, ts, json, yaml, markdown, css]
        pass_filenames: true

  - repo: https://github.com/Weburz/crisp
    rev: v1.0.0
    hooks:
      - id: crisp
        stages: [commit-msg]
        name: lint git-commit messages
