name: "Code QA Checks"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
      - review_requested

jobs:
  oxlint:
    name: Run Oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Oxlint
        run: pnpm lint

  oxfmt:
    name: Run Oxfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Oxfmt
        run: pnpm fmt:check

  typecheck:
    name: Run TypeCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Type-Check
        run: pnpm typecheck

  build:
    name: Run Build Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Verify Static Build
        env:
          NUXT_PUBLIC_SITE_URL: https://tech.weburz.com
        run: pnpm run generate
